### ISSUE TITLE
bug: `--reply`/`-re` flag not functioning

### ISSUE THREAD

**Issue by joegoldin** [baalimago/clai#2]
https://github.com/baalimago/clai/blob/2714332ed4082c4e184885de829c2f2a539e49e8/internal/setup_flags.go#L51

Looks like the reply flag isn't functioning? 
<img width="1122" alt="image" src="https://github.com/baalimago/clai/assets/1571956/82938e0f-55a4-4d3b-b86d-75a5bc95074d">

**Comment by baalimago** [comment]
I had a look at it, the `clai help` message was incorrect. I thought go supported double dash, [but it does not ](https://github.com/golang/go/issues/45484#issuecomment-817030414).

Please try again with `clai q <remember-msg>` -> `clai -reply q <recall-msg>`. I also updated the `clai help` message to not use double dashes.

**Comment by joegoldin** [comment]
Hm, I'm still seeing the same behaviour -- it looks like `~/.clai/conversations/prevQuery.json` only ever contains my custom prompt and the most recent chat message, it's not being appended to, even with `-reply`:
<img width="1166" alt="image" src="https://github.com/baalimago/clai/assets/1571956/d9d84230-42a2-41df-ac96-fc50bc931c10">

**Comment by joegoldin** [comment]
<img width="515" alt="image" src="https://github.com/baalimago/clai/assets/1571956/f4e614a1-3d37-4d84-b6d1-763201f9b95b">

**Comment by joegoldin** [comment]
<img width="489" alt="image" src="https://github.com/baalimago/clai/assets/1571956/8e498b33-22fb-49b1-a580-0e759e944601">

**Comment by joegoldin** [comment]
Thanks for taking a look!

**Comment by baalimago** [comment]
Alright I did some updating to the help debug this. Could you update to the latest version (v1.0.4+) and then run + show me the following:
1. `clai v`
2. `DEBUG_REPLY_MODE=1 clai q Remember this: basket` (or whatever you now want it to remember)
3. `DEBUG_REPLY_MODE=1 clai -re q "What did I ask you to remember?"`

**Comment by joegoldin** [comment]
<img width="1119" alt="image" src="https://github.com/baalimago/clai/assets/1571956/a0c935db-575b-4534-aff5-dbecac28b3d2">

Really appreciate you troubleshooting this -- `rask` is the most exciting feature here for me :D

**Comment by baalimago** [comment]
No worries! I think it's great to explore edge cases like these before I add too much other functionality, so that it has a strong foundation + debugging practice, so thanks for sticking with it!

It looks like the flag isn't properly processed, somehow. Note how it's still `reply mode active: false`, even though the flag is there. Could you please try running:
1. `clai -raw q Write something short` - This should result in output without markdown. I'm thinking that it might be a flag parsing issue in general
2. `DEBUG_REPLY_MODE=1 clai '-re' q What did I say last comment` - This should eliminate chance of the flag somehow being removed by some shell magic (never seen it, but who knows, might happen)
3. `DEBUG_REPLY_MODE=1 clai -re=true q What did I say last comment` - Explicitly set the flag to true, instead of relying on  the flag being implicitly set by simply existing

**Comment by joegoldin** [comment]
<img width="507" alt="image" src="https://github.com/baalimago/clai/assets/1571956/a58ee2f9-352a-4604-859d-b0fbfe31ba83">
<img width="1114" alt="image" src="https://github.com/baalimago/clai/assets/1571956/078dccd6-77eb-40ab-8950-6a8f2c5e67d6">

It does seem like it's ignoring the flag, specifically for reply mode. Maybe something else is forcing it false? I'm seeing the same behaviour in PowerShell on Windows 11 🤷

**Comment by joegoldin** [comment]
Ah, I think I found it -- https://github.com/baalimago/clai/blob/main/internal/setup.go#L74
![image](https://github.com/baalimago/clai/assets/1571956/0962452a-bde4-4861-a0e4-c254d8f8a4c4)

**Comment by joegoldin** [comment]
@baalimago 😄 https://github.com/baalimago/clai/pull/3
![image](https://github.com/baalimago/clai/assets/1571956/9fb52293-6d10-4719-a5ea-9a1bc1236fe3)
